"""Initial migration.

Revision ID: 32aa2a232310
Revises: 
Create Date: 2025-01-22 17:38:54.325185

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '32aa2a232310'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=30),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=30),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=30),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=30),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.String(length=30),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
