"""Other table changes.

Revision ID: 48ffb3ccb6ef
Revises: 32aa2a232310
Create Date: 2025-01-22 17:47:25.087336

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '48ffb3ccb6ef'
down_revision = '32aa2a232310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=30),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=30),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=30),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
